export const USERS_MUTATION = "USERS_MUTATION";

export const SIGN_UP_MUTATION = "SIGN_UP_MUTATION";

export const SIGN_IN_MUTATION = "SIGN_IN_MUTATION";

export const GET_USER_QUERY = "GET_USER_QUERY";

export const LOGOUT_MUTATION = "LOGOUT_MUTATION";

export const DELETE_USER_MUTATION = "DELETE_USER_MUTATION";

export const UPDATE_USER_MUTATION = "UPDATE_USER_MUTATION";

export const USERS_QUERY = "USERS_QUERY";
